### ISSUE TITLE
Sharevox - Ver. 0.2.0 - Macintosh version のでファルとさいるの完了ボタンは使えない。

### ISSUE THREAD

**Issue by ckjpn** [SHAREVOX/sharevox#11]
Macintosh version のでファルとスタイルの完了ボタンは使えない。
<img width="991" alt="Screen Shot 2023-02-24 at 13 32 18" src="https://user-images.githubusercontent.com/7934273/221092898-3ffd059a-7a24-4d81-a3b0-be5442bf994c.png">

**Comment by y-chan** [comment]
Issueありがとうございます！

把握済みの問題で、VOICEVOX側でも対応が打たれています。
VOICEVOX/voicevox#1197

SHAREVOXでも同様の解決策を適用しようと思っていますが、少し時間がかかりそうです。

**Comment by y-chan** [comment]
VOICEVOXのマージをしたので解決しました、closeします。
