### ISSUE TITLE
SHAREVOX 0.1.xの設定ファイルが残っている場合に設定が戻ってしまう

### ISSUE THREAD

**Issue by sabonerune** [SHAREVOX/sharevox#12]
## 不具合の内容

SHAREVOX 0.1.xの設定ファイルが残っている場合0.1.xの設定が現在の設定に上書きされてしまうため設定が元の状態に戻ってしまいます。

### 再現手順

- SHAREVOX 0.1.xを起動して終了する
- SHAREVOX 0.2.1を起動して設定を変更する
- SHAREVOX 0.2.1を再起動すると0.1.x時の設定に戻っている

### 期待動作

設定が正しく保存される

## SHAREVOXのバージョン

0.2.1 (CPU)
(恐らく0.2.0も?)

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

## その他

VOICEVOXは0.14で設定ファイルの保存場所を変更したがとSHAREVOXは0.2.0で変更したためマイグレーションの条件が間違ってしまっていることが原因だと思います。

https://github.com/SHAREVOX/sharevox/blob/3f72783d4ceada3868ac7b2706fecb5b188c5235/src/background/configMigration014.ts#L23-L40

**Comment by y-chan** [comment]
おっと！ありがとうございます...!

@sabonerune さん的にはどのように対応したほうがいいと思われますか...?:eyes:
例えば、プロジェクトファイルはVOICEVOXのマイグレーション処理を最大限に活かすべく、`voicevoxUpdateInfo.json`の最新バージョン値に基づいて処理しています。
設定ファイルも同じように処理したほうが良いと思うのですが、すでに0.1.x系の設定ファイルは0.1.xとして保存されているため、おそらくいきなりVOICEVOXと同じバージョン値を使うようにした場合不都合が起こる可能性がありそうです。
また、軽く調べた感じだとstoreのバージョンは`package.json`の情報に基づいて自動で決まるっぽいので、変更するのは難しいかもですね...

まあ、書き換えるのが`configMigration014.ts`の33行目と、`background.ts`の`migration`の部分で済みそうな気もするので、storeのバージョンに任意の値を使えなさそうであれば、SHAREVOXのバージョンに基づく処理に変更することが望ましいかも...?

ご意見伺いたい&もしよろしければ`sv-release-0.2`ブランチに宛ててPRを作成していただけると助かります...!

**Comment by sabonerune** [comment]
`electron-store`のドキュメントには書いていないようですが``projectVersion`が設定できるようです。
https://github.com/sindresorhus/electron-store/blob/166cd4b64298c69a9bfa0409ce86b98390ab6265/index.js#L56-L57

あとこのタイミングならバージョンを進める方向なら一気に変えても問題は起きないような気がします。
