### ISSUE TITLE
プログラムをサイレントにインストールするコマンドはありますか？

### ISSUE THREAD

**Issue by Exorcism0666** [SHAREVOX/sharevox#14]
- microsoft/winget-pkgs#133011
- microsoft/winget-pkgs#133013
- microsoft/winget-pkgs#133015

**Comment by y-chan** [comment]
> プログラムをサイレントにインストールするコマンドはありますか？

現状存在しません。
また、そのような機能を追加する予定はありません。

加えて、あなたの日本語は不自然なので、英語も併記することを推奨します。

---

Currently does not exist.
There are no plans to add such a feature.

In addition, your Japanese is unnatural, so I recommend that you also write in English.
