### ISSUE TITLE
ユーザから見える場所でVOICEVOX→SHAREVOXの更新漏れがある部分を修正する

### ISSUE THREAD

**Issue by task4233** [SHAREVOX/sharevox#7]
## 不具合の内容
このコミットから漏れた部分の修正
https://github.com/SHAREVOX/sharevox/commit/51de6c539fe1e2a7ae2d7dce8d1c8269cb7c2011

### 現象・ログ
- [報告ツイ](https://twitter.com/hicoushiki/status/1568572336315695106)

### 期待動作
SHAREVOXと表示されること

## VOICEVOXのバージョン
[SHAREVOX 0.1.1](https://github.com/SHAREVOX/sharevox/releases/tag/0.1.1)

## OSの種類/ディストリ/バージョン

- [x] Windows
- [x] macOS
- [x] Linux

## その他

- 他にもあるかも
- ユーザに見える面は必ずやるべきだと思う
   - `src/components` 以下
   - `.github/ISSUE_TEMPLATE/` 以下

**Comment by task4233** [comment]
関係ないのもあるかも

### .github以下
```bash
grep -irl "voicevox" ./.github
./.github/workflows/build.yml
./.github/ISSUE_TEMPLATE/featurerequest.md
./.github/ISSUE_TEMPLATE/bugreport.md
./.github/ISSUE_TEMPLATE/question.md
```

### ./src/components以下
```bash
./src/components/UpdateInfo.vue
./src/components/HelpDialog.vue
./src/components/CharacterOrderDialog.vue
./src/components/SettingDialog.vue
./src/components/HeaderBarCustomDialog.vue
```

**Comment by TakedaHiromasa** [comment]
発見場所まとめ
./src/components以下

- [x] 修正不要
https://github.com/SHAREVOX/sharevox/blob/9774550f9e9afee68959efdcdd06348cad861cae/src/components/HeaderBarCustomDialog.vue#L162-L166

- [x] 修正不要
https://github.com/SHAREVOX/sharevox/blob/9774550f9e9afee68959efdcdd06348cad861cae/src/components/HelpDialog.vue#L125-L129

- [x] 修正不要
https://github.com/SHAREVOX/sharevox/blob/9774550f9e9afee68959efdcdd06348cad861cae/src/components/SettingDialog.vue#L605

- [x] 修正不要
https://github.com/SHAREVOX/sharevox/blob/9774550f9e9afee68959efdcdd06348cad861cae/src/components/SettingDialog.vue#L768

- [x] 修正不要
`isVoicevox`というObjectが使われている箇所がいくつか
https://github.com/SHAREVOX/sharevox/blob/9774550f9e9afee68959efdcdd06348cad861cae/src/components/UpdateInfo.vue#L20-L24

- [x] 修正不要
https://github.com/SHAREVOX/sharevox/blob/9774550f9e9afee68959efdcdd06348cad861cae/src/components/UpdateInfo.vue#L32

**Comment by TakedaHiromasa** [comment]
発見場所まとめ
.github以下
- [ ] 修正不要
https://github.com/SHAREVOX/sharevox/blob/9774550f9e9afee68959efdcdd06348cad861cae/.github/ISSUE_TEMPLATE/bugreport.md?plain=1#L23

- [ ] 修正不要
https://github.com/SHAREVOX/sharevox/blob/9774550f9e9afee68959efdcdd06348cad861cae/.github/ISSUE_TEMPLATE/featurerequest.md?plain=1#L24

- [ ] 修正不要
https://github.com/SHAREVOX/sharevox/blob/9774550f9e9afee68959efdcdd06348cad861cae/.github/ISSUE_TEMPLATE/question.md?plain=1#L11

- [x] 修正不要
`.github/workflows/build.yml`いっぱい。目に触れる場所ではないので修正は不要かも。
https://github.com/SHAREVOX/sharevox/blob/9774550f9e9afee68959efdcdd06348cad861cae/.github/workflows/build.yml

**Comment by TakedaHiromasa** [comment]
**その他**
- [x] 修正不要
https://github.com/SHAREVOX/sharevox/blob/8f5fdef3a44994b1bb4f32f0fe03daaf507d04e1/build/installer_linux.sh#L2

- [x] 修正不要
https://github.com/SHAREVOX/sharevox/blob/8f5fdef3a44994b1bb4f32f0fe03daaf507d04e1/build/installer.nsh#L5

- [x] 修正不要
https://github.com/SHAREVOX/sharevox/blob/8f5fdef3a44994b1bb4f32f0fe03daaf507d04e1/build/installer.nsh#L36

- [ ] 修正不要
https://github.com/SHAREVOX/sharevox/blob/8f5fdef3a44994b1bb4f32f0fe03daaf507d04e1/public/qAndA.md?plain=1#L58-L60

- [x] 修正不要
コメントを削除します
https://github.com/SHAREVOX/sharevox/blob/8f5fdef3a44994b1bb4f32f0fe03daaf507d04e1/public/qAndA.md?plain=1#L124-L129
